name: item_dex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.10
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  rflutter_alert: ^2.0.7
  scroll_date_picker: ^3.7.3
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - .env
